CREATE TABLE USERS (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE KEY,
    PassHash BINARY(60) NOT NULL,
    Role VARCHAR(3) NOT NULL
);